#ifndef PX_CORE_STORAGE_ATTRIBUTE_H
#define PX_CORE_STORAGE_ATTRIBUTE_H

#include "import.h"

typedef enum PxFileMode
{
    PX_FILE_MODE_NONE = 0,

    PX_FILE_MODE_RD = 1 << 0,
    PX_FILE_MODE_WR = 1 << 1,
    PX_FILE_MODE_EX = 1 << 2,

    PX_FILE_MODE_RD_WR = PX_FILE_MODE_RD | PX_FILE_MODE_WR,
    PX_FILE_MODE_RD_EX = PX_FILE_MODE_RD | PX_FILE_MODE_EX,
    PX_FILE_MODE_WR_EX = PX_FILE_MODE_WR | PX_FILE_MODE_EX,

    PX_FILE_MODE_FULL =
        PX_FILE_MODE_RD | PX_FILE_MODE_WR | PX_FILE_MODE_EX,
}
PxFileMode;

typedef enum PxFileType
{
    PX_FILE_NONE,
    PX_FILE_SIMPLE,
    PX_FILE_DIRECTORY,
}
PxFileType;

#endif // PX_CORE_STORAGE_ATTRIBUTE_H
